import express from 'express';
import * as locationCtrl from '../controllers/location.controller';
import isAuthenticated from '../middlewares/authenticate';
import validate from '../config/joi.validate';
import schema from '../utils/validator';

const router = express.Router();

/**
 * @swagger
 * tags:
 *   - name: location
 *     description: locations operations
 */

/**
 * @swagger
 * definitions:
 *   Location:
 *     type: object
 *     properties:
 *       id:
 *         type: integer
 *         description: Unique identifier representing a specific locations
 *         example: 2
 *       status:
 *         type: integer
 *         description: status of the locations
 *         example: 1
 *       created_at:
 *         type: string
 *         format: date-time
 *         description: locations creation datetime
 *       updated_at:
 *         type: string
 *         format: date-time
 *         description: locations update datetime
 *   Error:
 *     type: object
 *     properties:
 *        message:
 *           type: string
 *        error:
 *           type: boolean
 *           default: true
 */

/**
 * @swagger
 * securityDefinitions:
 *   Bearer:
 *     description: |
 *            For accessing the API a valid JWT token must be passed in all the queries in
 *            the 'Authorization' header.
 *
 *
 *            A valid JWT token is generated by the API and returned as answer of a call
 *            to the route /auth/login giving a valid locations & password.
 *
 *
 *            The following syntax must be used in the 'Authorization' header:
 *
 *            Bearer xxxxxx.yyyyyyy.zzzzzz
 *     type: apiKey
 *     name: Authorization
 *     in: header
 *
 */

router.route('/location')

/**
 * @swagger
 * /location:
 *   post:
 *     tags:
 *       - locations
 *     summary: "Create a new location"
 *     security:
 *        - Bearer: []
 *     operationId: addlocations
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: body
 *         in: body
 *         description: Created locations object
 *         required: true
 *         schema:
 *           $ref: "#/definitions/locations"
 *     responses:
 *       200:
 *         description: OK
 *         schema:
 *           $ref: "#/definitions/locations"
 *       403:
 *          description: locations not found
 *          schema:
 *             $ref: '#/definitions/Error'
 */

    .post(validate(schema.storeLocations), (req, res) => {
        locationCtrl.add(req, res);
    })

    /**
     * @swagger
     * /locations:
     *   get:
     *     tags:
     *       - location
     *     summary: "List all location"
     *     operationId: findAll
     *     consumes:
     *       - application/json
     *     produces:
     *       - application/json
     *     parameters: []
     *     responses:
     *       200:
     *         description: OK
     *         schema:
     *            type: object
     */

    .get( (req, res) => {
        locationCtrl.findAll(req, res);
    });


router.route('/location:id')

/**
 * @swagger
 * /Locations/{id}:
 *   get:
 *     tags:
 *       - location
 *     summary: Find the location by ID
 *     operationId: findById
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: id
 *         in: path
 *         description: id of locations that needs to be fetched
 *         required: true
 *         type: integer
 *     responses:
 *       200:
 *         description: OK
 *         schema:
 *           $ref: "#/definitions/locations"
 *       404:
 *          description: locations not found
 *          schema:
 *             $ref: '#/definitions/Error'
 */

    .get( (req, res) => {
        locationCtrl.findById(req, res);
    })

    /**
     * @swagger
     * /locations/{id}:
     *   put:
     *     tags:
     *       - locations
     *     summary: "Update an existing location by ID"
     *     security:
     *       - Bearer: []
     *     operationId: update
     *     consumes:
     *       - application/json
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: id
     *         in: path
     *         description: id that need to be updated
     *         required: true
     *         type: integer
     *       - name: body
     *         in: body
     *         description: Updated locations object
     *         required: true
     *         schema:
     *           $ref: "#/definitions/locations"
     *     responses:
     *       200:
     *         description: OK
     *         schema:
     *           $ref: "#/definitions/locations"
     *       400:
     *         description: Invalid locations
     */

    .put(isAuthenticated, (req, res) => {
        locationCtrl.update(req, res);
    })

    /**
     * @swagger
     * /locations/{id}:
     *   delete:
     *     tags:
     *       - locations
     *     summary: Delete the location by ID
     *     security:
     *       - Bearer: []
     *     operationId: destroy
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: id
     *         in: path
     *         description: id of locations that needs to be deleted
     *         required: true
     *         type: integer
     *     responses:
     *       200:
     *         description: OK
     *       400:
     *          description: "Invalid ID"
     */

    .delete(isAuthenticated, (req, res) => {
        locationCtrl.destroy(req, res);
    });


export default router;